### ISSUE TITLE
The DBConfirm.TemplateGeneration tool fails to generate template for a table containing a nvarchar(max) column

### ISSUE THREAD

**Issue by jamie-burns** [Bungalow64/DBConfirm#41]
I have a table containing an Identity and nvarchar(max) column:

```sql
CREATE TABLE [dbo].[Titles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Titles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
```

Running DBConfirm.TemplateGeneration on this table results in an error:

```
PS C:\Git\Database1Tests> GenerateTemplatesSQLServer -d "Database1" -t "Titles" --dry-run                         
Using connection: SERVER=(local);DATABASE=Database1;Integrated Security=true;Connection Timeout=30;
Found table (dbo.Titles) and 2 columns
There has been an error
Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at DBConfirm.TemplateGeneration.Models.ColumnDefinition.TruncateLongString(String value) in /home/vsts/work/1/s/tools/TemplateGeneration.SQLServer/Models/ColumnDefinition.cs:line 138
   at DBConfirm.TemplateGeneration.Models.ColumnDefinition.GetDefaultText() in /home/vsts/work/1/s/tools/TemplateGeneration.SQLServer/Models/ColumnDefinition.cs:line 119
   at DBConfirm.TemplateGeneration.Models.ColumnDefinition.ToDefaultData() in /home/vsts/work/1/s/tools/TemplateGeneration.SQLServer/Models/ColumnDefinition.cs:line 163
   at DBConfirm.TemplateGeneration.Logic.Generator.<>c.<GenerateClass>b__11_5(ColumnDefinition p) in /home/vsts/work/1/s/tools/TemplateGeneration.SQLServer/Logic/Generator.cs:line 183
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at DBConfirm.TemplateGeneration.Logic.Generator.GenerateClass(IEnumerable`1 processedColumns, String schemaName, String tableName) in /home/vsts/work/1/s/tools/TemplateGeneration.SQLServer/Logic/Generator.cs:line 173
   at DBConfirm.TemplateGeneration.Logic.Generator.GenerateFile(IEnumerable`1 processedColumns, String schemaName, String tableName) in /home/vsts/work/1/s/tools/TemplateGeneration.SQLServer/Logic/Generator.cs:line 93
   at DBConfirm.TemplateGeneration.Logic.Generator.GenerateFileAsync() in /home/vsts/work/1/s/tools/TemplateGeneration.SQLServer/Logic/Generator.cs:line 59
   at DBConfirm.TemplateGeneration.Program.<>c.<<Main>b__0_0>d.MoveNext() in /home/vsts/work/1/s/tools/TemplateGeneration.SQLServer/Program.cs:line 18
```

The tool should be able to generate a template with both columns included.

**Comment by Bungalow64** [comment]
This is fixed in develop, and available in 0.1.2 pre-release.  Will release as 0.1.2 actual later today.
