### ISSUE TITLE
Cannot generates templates into a folder that doesn't exist

### ISSUE THREAD

**Issue by jamie-burns** [Bungalow64/DBConfirm#45]
When running the GenerateTemplatesSQLServer tool, if a destination is selected that doesn't exist (e.g., create a new project, then try to generate templates into a Templates directory that hasn't been created yet) then we get an error saying that the path can't be found:

````
PS C:\Git\TestProject\DBTests> GenerateTemplatesSQLServer -d "TestDB" -t "*" -n "DBTests.Templates" --destination Templates
Using connection: SERVER=(local);DATABASE=TestDB;Integrated Security=true;Connection Timeout=30;
Found table (dbo.User) and 9 columns
Class definition generated.  Saving...
There has been an error
Could not find a part of the path 'C:\Git\TestProject\DBTests\Templates\UserTemplate.cs'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at DBConfirm.TemplateGeneration.Logic.FileHelper.WriteAllText(String path, String contents) in /home/vsts/work/1/s/tools/TemplateGeneration.SQLServer/Logic/FileHelper.cs:line 10
   at DBConfirm.TemplateGeneration.Logic.Generator.GenerateFile(IEnumerable`1 processedColumns, String schemaName, String tableName) in /home/vsts/work/1/s/tools/TemplateGeneration.SQLServer/Logic/Generator.cs:line 112
   at DBConfirm.TemplateGeneration.Logic.Generator.GenerateFileAsync() in /home/vsts/work/1/s/tools/TemplateGeneration.SQLServer/Logic/Generator.cs:line 61
   at DBConfirm.TemplateGeneration.Program.<>c.<<Main>b__0_0>d.MoveNext() in /home/vsts/work/1/s/tools/TemplateGeneration.SQLServer/Program.cs:line 18
````

The tool should try and create the directory if it doesn't already exist.

**Comment by Bungalow64** [comment]
This is included in 0.1.3
